version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_CLIENT_ID=TUTAJ_TWOJE_ID.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=TUTAJ_TWÓJ_SEKRET
      - GOOGLE_REDIRECT_URL=https://hackathon-e7kx.onrender.com/api/v1/auth/google/callback
      - DB_URL=host=db user=admin password=secretpassword dbname=roguelike port=5432 sslmode=disable
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: roguelike
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
